config/routes.rb
Repairer::Application.routes.draw do

  get "estim/index"
  get "estim/showselects"
  get "maintenances/addexpart"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "register" => "users#new", :as => "register"
  resources :users, :sessions #, :admin
  
  resources :brands, :car_models, :production_years, :maintenances, :parts, :labors
  get "estimator/index"
  post "estimator/index"
  get "estimator/showselects"
  get "estimator" => "estimator#index"
  get "showselects" => "estimator#showselects"
  
  get "admin/index"
  get "admin" => "admin#index"
  
  get "admin/parse_csv"
  post "admin/parse_csv"
  get "admin/parse_maintenance_csv"
  post "admin/parse_maintenance_csv"
  root :to => "estimator#index"

  get "modifications/index"
  get "modifications" => "modifications#index"

  get "modifications/clear"
  get "modifications/search_ex_part"
  get "modifications/add_ex_part"

  ['create', 'update', 'new', 'edit', 'destroy'].each { |r|
    ['brand', 'car_model', 'production_year', 'maintenance', 'labor', 'part'].each { |c|
      get "#{c}s_ajax/#{r}"
    }
  }

end

app/models/part.rb
class Part < ActiveRecord::Base
  has_and_belongs_to_many :maintenances
  
  validates_uniqueness_of :name
end
# == Schema Information
#
# Table name: parts
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  layout 'admin'
  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parts }
    end
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
    @part = Part.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @part }
    end
  end

  # GET /parts/new
  # GET /parts/new.json
  def new
    @part = Part.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @part }
    end
  end

  # GET /parts/1/edit
  def edit
    @part = Part.find(params[:id])
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(params[:part])

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render json: @part, status: :created, location: @part }
      else
        format.html { render action: "new" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parts/1
  # PUT /parts/1.json
  def update
    @part = Part.find(params[:id])

    respond_to do |format|
      if @part.update_attributes(params[:part])
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part = Part.find(params[:id])
    @part.destroy

    respond_to do |format|
      format.html { redirect_to parts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%= simple_form_for(@part) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/parts/edit.html.erb
<h1>Editing part</h1>

<%= render 'form' %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

app/views/parts/index.html.erb
<h1>Listing parts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parts.each do |part| %>
  <tr>
    <td><%= part.name %></td>
    <td><%= part.description %></td>
    <td><%= link_to 'Show', part %></td>
    <td><%= link_to 'Edit', edit_part_path(part) %></td>
    <td><%= link_to 'Destroy', part, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Part', new_part_path %>

app/views/parts/new.html.erb
<h1>New part</h1>

<%= render 'form' %>

<%= link_to 'Back', parts_path %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @part.name %>
</p>

<p>
  <b>Description:</b>
  <%= @part.description %>
</p>


<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>