config/routes.rb
Repairer::Application.routes.draw do

  get "estim/index"
  get "estim/showselects"
  get "maintenances/addexpart"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "register" => "users#new", :as => "register"
  resources :users, :sessions #, :admin
  
  resources :brands, :car_models, :production_years, :maintenances, :parts, :labors
  get "estimator/index"
  post "estimator/index"
  get "estimator/showselects"
  get "estimator" => "estimator#index"
  get "showselects" => "estimator#showselects"
  
  get "admin/index"
  get "admin" => "admin#index"
  
  get "admin/parse_csv"
  post "admin/parse_csv"
  get "admin/parse_maintenance_csv"
  post "admin/parse_maintenance_csv"
  root :to => "estimator#index"

  get "modifications/index"
  get "modifications" => "modifications#index"

  get "modifications/clear"
  get "modifications/search_ex_part"
  get "modifications/add_ex_part"

  ['create', 'update', 'new', 'edit', 'destroy'].each { |r|
    ['brand', 'car_model', 'production_year', 'maintenance', 'labor', 'part'].each { |c|
      get "#{c}s_ajax/#{r}"
    }
  }

end

app/models/brand.rb
# encoding: utf-8
class Brand < ActiveRecord::Base
  attr_accessible :name, :description, :logo
  
  has_many :car_models, :dependent => :destroy
  validates_uniqueness_of :name, :on => :create, :message => "Название должно быть уникальным"
  # accepts_nested_attributes_for :car_models
  accepts_nested_attributes_for :car_models, :allow_destroy => true, :reject_if => proc { |a| a[:name].blank? }
  
  mount_uploader :logo, LogoUploader
  
  # Возвращает true или false, в зависимости от того, есть ли у данного брэнда модель
  # с названием car_model_name
  def has_car_model?(car_model_name)
    arr = []
    self.car_models.each do |car_model|
      arr << car_model.name
    end
    arr.include?(car_model_name)
  end
end
# == Schema Information
#
# Table name: brands
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  load_and_authorize_resource
  
  # GET /brands
  # GET /brands.json
  layout 'admin'
  def index
    # @brands = Brand.all
    # authorize! :update, @brands

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new
    # 3.times do
    #    car_model = @brand.car_models.build
    #    4.times { car_model.production_years.build }
    # end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render json: @brand, status: :created, location: @brand }
      else
        format.html { render action: "new" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :ok }
    end
  end
end

app/helpers/brands_helper.rb
module BrandsHelper

end

app/views/brands/_car_model_fields.html.erb
<div class="nested-fields">
        <%= f.input :name %>
        <%= f.input :description, :as => :text, :input_html => { :rows => 3 } %>
        <%= link_to_remove_association "удалить модель", f %>
        <h3>Годы выпуска</h3>
        <%= f.simple_fields_for :production_years do |production_year| %>
            <%= render 'production_year_fields', :f => production_year %>
        <% end %>
        <div class="links">
            <%= link_to_add_association "добавить год выпуска", f, :production_years %><br />
        </div>
</div>

app/views/brands/_form.html.erb
# encoding: utf-8
<%= simple_form_for @brand do |f| %>
        <%= f.input :name, :label => "Имя" %>
        <%= f.input :description, :label => "Описание" %>
        <%= f.file_field :logo, :label => 'Логотипчег' %>
        <h3>Модели</h3>
        <%= f.simple_fields_for :car_models do |car_model| %>
            <%= render 'car_model_fields', :f => car_model %>
        <% end %>
        <div class="links">
            <%= link_to_add_association "Добавить модель", f, :car_models %>
        </div>
        <%= f.button :submit %>
<% end %>

app/views/brands/_simple_form.html.erb
<%= simple_form_for @brand, :remote => true do |f| %>
        <%= f.input :name, :label => "Имя", :input_html => { :size => 20 } %>
        <%= f.button :submit %>
<% end %>

app/views/brands/edit.html.erb
# encoding: utf-8
<h1>Редактирование брэнда <%= @brand.name %></h1>

<%= render 'form' %>

<%= link_to 'Показать', @brand %> |
<%= link_to 'Назад', brands_path %>

app/views/brands/index.html.erb
# encoding: utf-8
<h1>Список брэндов</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @brands.each do |brand| %>
  <tr>
    <td><%= brand.name %></td>
    <td><%= image_tag brand.logo_url.to_s unless brand.logo.blank? %></td>
    <td><%= link_to 'Показать', brand %></td>
    <td>
        <% if can? :manage, brand %>
            <%= link_to 'Редактировать', edit_brand_path(brand) %>
        <% end %>
    </td>
    <td><%= link_to 'Удалить', brand, :method => 'delete', :confirm => "Вы уверены?" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Добавить новый брэнд', new_brand_path %>

app/views/brands/new.html.erb
# encoding: utf-8
<h1>Новый брэнд</h1>

<%= render 'form' %>

<%= link_to 'Назад', brands_path %>

app/views/brands/show.html.erb
# encoding: utf-8
<p id="notice"><%= notice %></p>
<p>
  <b>Название:</b>
  <%= @brand.name %>
</p>
<ol>
    <% if !@brand.car_models.blank? %>
      <% for car_model in @brand.car_models %>
        <li><%= car_model.name %></li>
        <ul>
            <% if !car_model.production_years.blank? %>
              <% for production_year in car_model.production_years %>
                <li><%= production_year.year %></li>
              <% end %>
            <% else %>
              
            <% end %>
            
        </ul>
      <% end %>
    <% else %>
      
    <% end %>
    
</ol>


<%= link_to 'Редактировать', edit_brand_path(@brand) %> |
<%= link_to 'Назад', brands_path %>