config/routes.rb
Repairer::Application.routes.draw do

  get "estim/index"
  get "estim/showselects"
  get "maintenances/addexpart"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "register" => "users#new", :as => "register"
  resources :users, :sessions #, :admin
  
  resources :brands, :car_models, :production_years, :maintenances, :parts, :labors
  get "estimator/index"
  post "estimator/index"
  get "estimator/showselects"
  get "estimator" => "estimator#index"
  get "showselects" => "estimator#showselects"
  
  get "admin/index"
  get "admin" => "admin#index"
  
  get "admin/parse_csv"
  post "admin/parse_csv"
  get "admin/parse_maintenance_csv"
  post "admin/parse_maintenance_csv"
  root :to => "estimator#index"

  get "modifications/index"
  get "modifications" => "modifications#index"

  get "modifications/clear"
  get "modifications/search_ex_part"
  get "modifications/add_ex_part"

  ['create', 'update', 'new', 'edit', 'destroy'].each { |r|
    ['brand', 'car_model', 'production_year', 'maintenance', 'labor', 'part'].each { |c|
      get "#{c}s_ajax/#{r}"
    }
  }

end

app/models/labor.rb
# encoding: utf-8
class Labor < ActiveRecord::Base
  belongs_to :maintenance
  
  validate :validate_name_uniqueness_inside_maintenance

  def validate_name_uniqueness_inside_maintenance
    self.errors.add(:name, "работы должно быть уникально, в рамках родительского обслуживания") if self.maintenance.has_labor?(self.name)
  end
end
# == Schema Information
#
# Table name: labors
#
#  id             :integer         not null, primary key
#  name           :string(255)
#  description    :string(255)
#  maintenance_id :integer
#  created_at     :datetime
#  updated_at     :datetime
#

app/controllers/labors_controller.rb
class LaborsController < ApplicationController
  layout 'admin'
  # GET /labors
  # GET /labors.json
  def index
    @labors = Labor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @labors }
    end
  end

  # GET /labors/1
  # GET /labors/1.json
  def show
    @labor = Labor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @labor }
    end
  end

  # GET /labors/new
  # GET /labors/new.json
  def new
    @labor = Labor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @labor }
    end
  end

  # GET /labors/1/edit
  def edit
    @labor = Labor.find(params[:id])
  end

  # POST /labors
  # POST /labors.json
  def create
    @labor = Labor.new(params[:labor])

    respond_to do |format|
      if @labor.save
        format.html { redirect_to @labor, notice: 'Labor was successfully created.' }
        format.json { render json: @labor, status: :created, location: @labor }
      else
        format.html { render action: "new" }
        format.json { render json: @labor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /labors/1
  # PUT /labors/1.json
  def update
    @labor = Labor.find(params[:id])

    respond_to do |format|
      if @labor.update_attributes(params[:labor])
        format.html { redirect_to @labor, notice: 'Labor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @labor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labors/1
  # DELETE /labors/1.json
  def destroy
    @labor = Labor.find(params[:id])
    @labor.destroy

    respond_to do |format|
      format.html { redirect_to labors_url }
      format.json { head :ok }
    end
  end
end

app/helpers/labors_helper.rb
module LaborsHelper
end

app/views/labors/_form.html.erb
<%= simple_form_for(@labor) do |f| %>
  <%= f.association :maintenance, :collection => Maintenance.all.map \
   { |r| [r.header, r.id, r.id] }, :prompt => "Выберите Обслуживание" %>

  <div class="inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/labors/edit.html.erb
<h1>Editing labor</h1>

<%= render 'form' %>

<%= link_to 'Show', @labor %> |
<%= link_to 'Back', labors_path %>

app/views/labors/index.html.erb
<h1>Listing labors</h1>

<table>
  <tr>
    <th>Модификация</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @labors.each do |labor| %>
  <tr>
    <td><%= labor.maintenance.nil? ? 'Глюк, видимо нет родителя' : labor.maintenance.header %></td>
    <td><%= labor.name %></td>
    <td><%= labor.description %></td>
    <td><%= link_to 'Show', labor %></td>
    <td><%= link_to 'Edit', edit_labor_path(labor) %></td>
    <td><%= link_to 'Destroy', labor, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Labor', new_labor_path %>

app/views/labors/new.html.erb
<h1>New labor</h1>

<%= render 'form' %>

<%= link_to 'Back', labors_path %>

app/views/labors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Модфикация:</b>
  <%= @labor.maintenance.header %>
</p>

<p>
  <b>Название:</b>
  <%= @labor.name %>
</p>

<p>
  <b>Описание:</b>
  <%= @labor.description %>
</p>


<%= link_to 'Edit', edit_labor_path(@labor) %> |
<%= link_to 'Back', labors_path %>